//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalePerson
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalePerson()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int SalePersonId { get; set; }
        public string SalePersonName { get; set; }
        public string SalePersonPhone { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string UserId { get; set; }
        public string Password { get; set; }
        public int StoreId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        public virtual Role Role { get; set; }
        public virtual Store Store { get; set; }
    }
}
